class_dic = {
    '1': 'atr',
    '2': 'epithelial cell',
    '3': 'ncc',
    '4': 'neutrophile',
    '5': 'lymphocyte',
    '6': 'clusters',
    '7': 'clue',
    '8': 'others',
    '9': 'sus',
    '10': 'middle cell',
    '11': 'gland cell',
    '12': 'blood',
    '13': 'hs',
    '14': 'zgnm',
    '15': 'basical cell',
    '16': 'hsil',
    '17': 'koilocyte cell',
    '18': 'can',
    '19': 'lvpao',
    '20': 'agc',
    '21': 'acti',
    '22': 'agc',
    '23': 'tri',
    '24': 'fun',
    '25': 'a-h',
    '26': 'xm',
    '27': 'small cell',
    '28': 'bal',
    '29': 'ca',
}
